### ISSUE TITLE
use of mapping for geometry sets wrong type for geometry on Item

### ISSUE THREAD

**Issue by philvarner** [stactools-packages/cop-dem#11]
https://github.com/stactools-packages/cop-dem/blob/f7e2207f610f9c5ca2fa828b9d22e5a106493b9b/src/stactools/cop_dem/stac.py#L38

mapping is used to set the geometry, but mapping returns a tuple of tuples instead of list of lists. 

Fix is to run this code against the mapping to convert it:

```
def listify(t):
    return list(map(listify, t)) if isinstance(t, (list, tuple)) else t
```

**Comment by gadomski** [comment]
Would it make sense to push a fix in `PySTAC` so that it converts geometries to the correct type on the way in?

**Comment by philvarner** [comment]
yes, as long as there's not currently an expectation that the Item will be referencing the same object you passed in

**Comment by gadomski** [comment]
> as long as there's not currently an expectation that the Item will be referencing the same object you passed in

I think it's reasonable to expect an `Item` to take ownership of anything passed in to its constructor. I don't think we ever explicitly state that, however.

/me wanders off, grumbling about Python's ownership model and wishing he were writing 🦀

**Comment by philvarner** [comment]
Yeah, it's a horrible practice to continue to reference a mutable object a user passed into you, but don't we do that elsewhere with the "clone this / don't clone this" flag (I forget what it actually is)?

Rust's ownership model is just 👩🏻‍🍳 💋  -- it's a rigorous compromise between the OO "pass the mutable world around" and functional everything-is-immutable-so-we're-constantly-cloning-everything models.

**Comment by philvarner** [comment]
accidentally hit the close instead of just comment.

**Comment by philvarner** [comment]
I don't think this is actually an issue -- there shouldn't be a problem with using a tuple for the geometry instead of a list, just because we think of list as more closely mapping to a JSON array.

In the case I brought up, I think the real issue is that stac-validator *assumes* that it's a list when doing validation of a dict, and the fix should really be there.
